/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/collections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['GetCollectionsRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateCollectionProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['CreateCollectionExecuteResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/followed/reorder': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ReorderFollowedCollectionsProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ReorderFollowedCollectionsExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/owned/reorder': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ReorderCollectionsProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ReorderOwnedCollectionsExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateCollectionProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UpdateCollectionExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['DeleteCollectionExecuteResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/{id}/links/reorder': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['ReorderCollectionLinksProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ReorderCollectionLinksExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['HealthRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/links': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateLinkApiProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['CreateLinkExecuteResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/links/favorites': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['GetFavoriteLinksRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/links/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateLinkProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UpdateLinkExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['DeleteLinkExecuteResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/links/{id}/collection': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['MoveLinkProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['MoveLinkExecuteResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/links/{id}/collections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string | number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['AddLinkToCollectionProps'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AddLinkToCollectionExecuteResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					since?: string | null;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['SyncRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/tokens/check': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ApiTokenRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/extension/authorize': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query: {
					redirect_uri: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AuthorizeExtensionRenderResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AddLinkToCollectionExecuteResponse: {
			message: string;
		};
		AddLinkToCollectionProps: {
			collectionId: string | number;
		};
		ApiTokenRenderResponse: {
			message: string;
		};
		AuthorizeExtensionRenderResponse: unknown;
		CreateCollectionExecuteResponse: {
			collection: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				createdAt: string;
				description: string | null;
				icon: string | null;
				id: number;
				isDefault: boolean;
				isOwner: boolean;
				links?: {
					authorId: number;
					clicks: number;
					collectionIds: number[];
					createdAt: string;
					description: string | null;
					favorite: boolean;
					id: number;
					lastClickedAt: string | null;
					name: string;
					updatedAt: string;
					url: string;
				}[];
				name: string;
				position: number;
				updatedAt: string;
				visibility: components['schemas']['Visibility'];
			};
			message: string;
		};
		CreateCollectionProps: {
			description: string | null;
			icon?: string | null;
			name: string;
			visibility: components['schemas']['Visibility'];
		};
		CreateLinkApiProps: {
			collectionIds?: (string | number)[] | null;
			description?: string | null;
			favorite: string | number | boolean;
			name: string;
			url: string;
		};
		CreateLinkExecuteResponse: {
			link: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				clicks: number;
				collectionIds: number[];
				createdAt: string;
				description: string | null;
				favorite: boolean;
				id: number;
				lastClickedAt: string | null;
				name: string;
				updatedAt: string;
				url: string;
			};
			message: string;
		};
		DeleteCollectionExecuteResponse: {
			message: string;
		};
		DeleteLinkExecuteResponse: {
			message: string;
		};
		GetCollectionsRenderResponse: {
			data: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				createdAt: string;
				description: string | null;
				icon: string | null;
				id: number;
				isDefault: boolean;
				isOwner: boolean;
				links?: {
					authorId: number;
					clicks: number;
					collectionIds: number[];
					createdAt: string;
					description: string | null;
					favorite: boolean;
					id: number;
					lastClickedAt: string | null;
					name: string;
					updatedAt: string;
					url: string;
				}[];
				name: string;
				position: number;
				updatedAt: string;
				visibility: components['schemas']['Visibility'];
			}[];
			followedCollections: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				createdAt: string;
				description: string | null;
				icon: string | null;
				id: number;
				isDefault: boolean;
				isOwner: boolean;
				links?: {
					authorId: number;
					clicks: number;
					createdAt: string;
					description: string | null;
					favorite: boolean;
					id: number;
					lastClickedAt: string | null;
					name: string;
					updatedAt: string;
					url: string;
				}[];
				name: string;
				updatedAt: string;
				visibility: components['schemas']['Visibility'];
			}[];
		};
		GetFavoriteLinksRenderResponse: {
			data: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				clicks: number;
				collectionIds: number[];
				createdAt: string;
				description: string | null;
				favorite: boolean;
				id: number;
				lastClickedAt: string | null;
				name: string;
				updatedAt: string;
				url: string;
			}[];
		};
		HealthRenderResponse: {
			capabilities: {
				apiSearch: boolean;
				clickTracking: boolean;
				extensionAuthHandoff: boolean;
				syncDelta: boolean;
			};
			isHealthy: boolean;
		};
		MoveLinkExecuteResponse: {
			message: string;
		};
		MoveLinkProps: {
			fromCollectionId: string | number;
			toCollectionId: string | number;
		};
		ReorderCollectionLinksExecuteResponse: {
			message: string;
		};
		ReorderCollectionLinksProps: {
			linkIds: (string | number)[];
		};
		ReorderCollectionsProps: {
			collectionIds: (string | number)[];
			visibility: components['schemas']['Visibility'];
		};
		ReorderFollowedCollectionsExecuteResponse: {
			message: string;
		};
		ReorderFollowedCollectionsProps: {
			collectionIds: (string | number)[];
		};
		ReorderOwnedCollectionsExecuteResponse: {
			message: string;
		};
		SyncRenderResponse: {
			collections: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				createdAt: string;
				description: string | null;
				icon: string | null;
				id: number;
				isDefault: boolean;
				isOwner: boolean;
				name: string;
				updatedAt: string;
				visibility: components['schemas']['Visibility'];
			}[];
			deletedCollectionIds: number[];
			deletedLinkIds: number[];
			isFullSync: boolean;
			links: {
				author?: {
					avatarUrl: string | null;
					createdAt: string;
					fullname: string;
					id: number;
					isAdmin: boolean;
					updatedAt: string;
				};
				authorId: number;
				clicks: number;
				collectionIds: number[];
				createdAt: string;
				description: string | null;
				favorite: boolean;
				id: number;
				lastClickedAt: string | null;
				name: string;
				updatedAt: string;
				url: string;
			}[];
			syncedAt: string;
		};
		UpdateCollectionExecuteResponse: {
			message: string;
		};
		UpdateCollectionProps: {
			description: string | null;
			icon?: string | null;
			name: string;
			visibility: components['schemas']['Visibility'];
		};
		UpdateLinkExecuteResponse: {
			message: string;
		};
		UpdateLinkProps: {
			collectionIds: (string | number)[];
			description?: string | null;
			favorite: string | number | boolean;
			name: string;
			url: string;
		};
		/** @enum {string} */
		Visibility: 'PRIVATE' | 'PUBLIC';
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
