name: dev-stack
services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=myemail@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=a12345678
    depends_on:
      - postgres
    volumes:
      - ./docker-config/servers_pgadmin.json:/pgadmin4/servers.json
    ports:
      - '5050:80'

volumes:
  postgres_volume:
    name: postgres_test_dev_stack
