name: app-dev
services:
  postgres:
    restart: always
    image: postgres:18
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_DATABASE}']
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 500ms
    volumes:
      - postgres-volume:/var/lib/postgresql
    ports:
      - '${DB_PORT}:5432'

volumes:
  postgres-volume:
