/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    ActivityJournal: () => import('#controllers/admin/activity_journal_controller'),
    Admin: () => import('#controllers/admin/admin_controller'),
    AuthJournal: () => import('#controllers/admin/auth_journal_controller'),
    BulkDeleteUsers: () => import('#controllers/admin/bulk_delete_users_controller'),
    RevokeAccountAccess: () => import('#controllers/admin/revoke_account_access_controller'),
    SendAccountPasswordReset: () => import('#controllers/admin/send_account_password_reset_controller'),
    SetAccountRole: () => import('#controllers/admin/set_account_role_controller'),
    Status: () => import('#controllers/admin/status_controller'),
    VerifyAccountEmail: () => import('#controllers/admin/verify_account_email_controller'),
  },
  api: {
    collections: {
      CreateCollection: () => import('#controllers/api/collections/create_collection_controller'),
      DeleteCollection: () => import('#controllers/api/collections/delete_collection_controller'),
      GetCollections: () => import('#controllers/api/collections/get_collections_controller'),
      ReorderCollectionLinks: () => import('#controllers/api/collections/reorder_collection_links_controller'),
      ReorderFollowedCollections: () => import('#controllers/api/collections/reorder_followed_collections_controller'),
      ReorderOwnedCollections: () => import('#controllers/api/collections/reorder_owned_collections_controller'),
      UpdateCollection: () => import('#controllers/api/collections/update_collection_controller'),
    },
    health: {
      Health: () => import('#controllers/api/health/health_controller'),
    },
    links: {
      AddLinkToCollection: () => import('#controllers/api/links/add_link_to_collection_controller'),
      CreateLink: () => import('#controllers/api/links/create_link_controller'),
      DeleteLink: () => import('#controllers/api/links/delete_link_controller'),
      GetFavoriteLinks: () => import('#controllers/api/links/get_favorite_links_controller'),
      MoveLink: () => import('#controllers/api/links/move_link_controller'),
      UpdateLink: () => import('#controllers/api/links/update_link_controller'),
    },
    sync: {
      Sync: () => import('#controllers/api/sync/sync_controller'),
    },
    tokens: {
      ApiToken: () => import('#controllers/api/tokens/api_token_controller'),
    },
  },
  auth: {
    CancelEmailChange: () => import('#controllers/auth/cancel_email_change_controller'),
    ChangePassword: () => import('#controllers/auth/change_password_controller'),
    ConfirmEmailChange: () => import('#controllers/auth/confirm_email_change_controller'),
    GoogleAuth: () => import('#controllers/auth/google_auth_controller'),
    LinkProvider: () => import('#controllers/auth/link_provider_controller'),
    Login: () => import('#controllers/auth/login_controller'),
    Logout: () => import('#controllers/auth/logout_controller'),
    OauthCallback: () => import('#controllers/auth/oauth_callback_controller'),
    Register: () => import('#controllers/auth/register_controller'),
    RequestEmailChange: () => import('#controllers/auth/request_email_change_controller'),
    RequestPasswordReset: () => import('#controllers/auth/request_password_reset_controller'),
    ResendVerification: () => import('#controllers/auth/resend_verification_controller'),
    ResetPassword: () => import('#controllers/auth/reset_password_controller'),
    SetPassword: () => import('#controllers/auth/set_password_controller'),
    SudoMode: () => import('#controllers/auth/sudo_mode_controller'),
    SudoModeGoogle: () => import('#controllers/auth/sudo_mode_google_controller'),
    UnlinkProvider: () => import('#controllers/auth/unlink_provider_controller'),
    VerifyEmail: () => import('#controllers/auth/verify_email_controller'),
  },
  collections: {
    CreateCollection: () => import('#controllers/collections/create_collection_controller'),
    DeleteCollection: () => import('#controllers/collections/delete_collection_controller'),
    FollowCollection: () => import('#controllers/collections/follow_collection_controller'),
    ReorderCollectionLinks: () => import('#controllers/collections/reorder_collection_links_controller'),
    ReorderFollowedCollections: () => import('#controllers/collections/reorder_followed_collections_controller'),
    ReorderOwnedCollections: () => import('#controllers/collections/reorder_owned_collections_controller'),
    ShowCollection: () => import('#controllers/collections/show_collection_controller'),
    ShowInbox: () => import('#controllers/collections/show_inbox_controller'),
    UnfollowCollection: () => import('#controllers/collections/unfollow_collection_controller'),
    UpdateCollection: () => import('#controllers/collections/update_collection_controller'),
  },
  extension: {
    AuthorizeExtension: () => import('#controllers/extension/authorize_extension_controller'),
  },
  favicons: {
    Favicons: () => import('#controllers/favicons/favicons_controller'),
  },
  favorites: {
    ShowFavorites: () => import('#controllers/favorites/show_favorites_controller'),
  },
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Home: () => import('#controllers/home_controller'),
  links: {
    AddLinkToCollection: () => import('#controllers/links/add_link_to_collection_controller'),
    CreateLink: () => import('#controllers/links/create_link_controller'),
    DeleteLink: () => import('#controllers/links/delete_link_controller'),
    GetLinks: () => import('#controllers/links/get_links_controller'),
    MoveLink: () => import('#controllers/links/move_link_controller'),
    ToggleFavorite: () => import('#controllers/links/toggle_favorite_controller'),
    UpdateLink: () => import('#controllers/links/update_link_controller'),
    VisitLink: () => import('#controllers/links/visit_link_controller'),
  },
  sharedCollections: {
    SharedCollections: () => import('#controllers/shared_collections/shared_collections_controller'),
  },
  userSettings: {
    DeleteUserAccount: () => import('#controllers/user_settings/delete_user_account_controller'),
    ExportUserData: () => import('#controllers/user_settings/export_user_data_controller'),
    ImportUserData: () => import('#controllers/user_settings/import_user_data_controller'),
    ShowUserSettings: () => import('#controllers/user_settings/show_user_settings_controller'),
  },
  user: {
    CreateApiToken: () => import('#controllers/user/create_api_token_controller'),
    DeleteApiToken: () => import('#controllers/user/delete_api_token_controller'),
    DestroySession: () => import('#controllers/user/destroy_session_controller'),
  },
}
