/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CollectionFollowerSchema extends BaseModel {
  static $columns = ['collectionId', 'createdAt', 'userId'] as const
  $columns = CollectionFollowerSchema.$columns
  @column({ isPrimary: true })
  declare collectionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare userId: number
}

export class CollectionSchema extends BaseModel {
  static $columns = ['authorId', 'createdAt', 'description', 'icon', 'id', 'name', 'updatedAt', 'visibility'] as const
  $columns = CollectionSchema.$columns
  @column()
  declare authorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visibility: any | null
}

export class LinkSchema extends BaseModel {
  static $columns = ['authorId', 'collectionId', 'createdAt', 'description', 'favorite', 'id', 'name', 'updatedAt', 'url'] as const
  $columns = LinkSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare collectionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare favorite: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'expiresAt', 'id', 'userId'] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'id', 'isAdmin', 'lastSeenAt', 'name', 'nickName', 'providerId', 'providerType', 'token', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare nickName: string | null
  @column()
  declare providerId: string
  @column()
  declare providerType: string
  @column()
  declare token: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
