/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditEventSchema extends BaseModel {
  static $columns = ['actorId', 'createdAt', 'id', 'ip', 'metadata', 'subjectId', 'subjectType', 'type', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = AuditEventSchema.$columns
  @column()
  declare actorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column()
  declare metadata: any | null
  @column()
  declare subjectId: number | null
  @column()
  declare subjectType: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CollectionFollowerSchema extends BaseModel {
  static $columns = ['collectionId', 'createdAt', 'position', 'userId'] as const
  $columns = CollectionFollowerSchema.$columns
  @column({ isPrimary: true })
  declare collectionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare position: number
  @column()
  declare userId: number
}

export class CollectionLinkSchema extends BaseModel {
  static $columns = ['collectionId', 'createdAt', 'linkId', 'position'] as const
  $columns = CollectionLinkSchema.$columns
  @column({ isPrimary: true })
  declare collectionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare linkId: number
  @column()
  declare position: number
}

export class CollectionSchema extends BaseModel {
  static $columns = ['authorId', 'createdAt', 'description', 'icon', 'id', 'isDefault', 'name', 'position', 'updatedAt', 'visibility'] as const
  $columns = CollectionSchema.$columns
  @column()
  declare authorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visibility: any | null
}

export class FaviconEntrySchema extends BaseModel {
  static $columns = ['byteSize', 'contentHash', 'contentType', 'createdAt', 'etag', 'id', 'lastModified', 'origin', 'resolvedAt', 'resolvedUrl', 'source', 'updatedAt'] as const
  $columns = FaviconEntrySchema.$columns
  @column()
  declare byteSize: number
  @column()
  declare contentHash: string
  @column()
  declare contentType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare etag: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastModified: string | null
  @column()
  declare origin: string
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedUrl: string | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LinkSchema extends BaseModel {
  static $columns = ['authorId', 'clicks', 'createdAt', 'description', 'favorite', 'id', 'lastClickedAt', 'name', 'updatedAt', 'url'] as const
  $columns = LinkSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare clicks: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare favorite: boolean
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastClickedAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class OauthAuthSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'linkedAt', 'provider', 'providerUserId', 'updatedAt', 'userId'] as const
  $columns = OauthAuthSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare linkedAt: DateTime
  @column()
  declare provider: string
  @column()
  declare providerUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OneTimeTokenSchema extends BaseModel {
  static $columns = ['consumedAt', 'createdAt', 'expiresAt', 'id', 'newEmail', 'tokenHash', 'type', 'updatedAt', 'userId'] as const
  $columns = OneTimeTokenSchema.$columns
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newEmail: string | null
  @column()
  declare tokenHash: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PasswordAuthSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'password', 'passwordChangedAt', 'updatedAt', 'userId'] as const
  $columns = PasswordAuthSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SyncDeletionSchema extends BaseModel {
  static $columns = ['authorId', 'deletedAt', 'entityId', 'entityType', 'id'] as const
  $columns = SyncDeletionSchema.$columns
  @column()
  declare authorId: number
  @column.dateTime()
  declare deletedAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'expiresAt', 'id', 'userId'] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'id', 'isAdmin', 'lastSeenAt', 'name', 'nickName', 'pendingDeletionAt', 'pendingDeletionRequestedById', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare nickName: string | null
  @column.dateTime()
  declare pendingDeletionAt: DateTime | null
  @column()
  declare pendingDeletionRequestedById: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
