/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class AuthAccessTokenSchema extends BaseModel {
	static $columns = [
		'id',
		'tokenableId',
		'type',
		'name',
		'hash',
		'abilities',
		'createdAt',
		'updatedAt',
		'lastUsedAt',
		'expiresAt',
	] as const;
	$columns = AuthAccessTokenSchema.$columns;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare tokenableId: number;
	@column()
	declare type: string;
	@column()
	declare name: string | null;
	@column()
	declare hash: string;
	@column()
	declare abilities: string;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column.dateTime()
	declare lastUsedAt: DateTime | null;
	@column.dateTime()
	declare expiresAt: DateTime | null;
}

export class CollectionFollowerSchema extends BaseModel {
	static $columns = ['collectionId', 'userId', 'createdAt'] as const;
	$columns = CollectionFollowerSchema.$columns;
	@column()
	declare collectionId: number;
	@column()
	declare userId: number;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
}

export class CollectionSchema extends BaseModel {
	static $columns = [
		'name',
		'description',
		'visibility',
		'authorId',
		'id',
		'createdAt',
		'updatedAt',
		'icon',
	] as const;
	$columns = CollectionSchema.$columns;
	@column()
	declare name: string;
	@column()
	declare description: string | null;
	@column()
	declare visibility: any | null;
	@column()
	declare authorId: number | null;
	@column({ isPrimary: true })
	declare id: number;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column()
	declare icon: string | null;
}

export class LinkSchema extends BaseModel {
	static $columns = [
		'name',
		'description',
		'url',
		'favorite',
		'collectionId',
		'authorId',
		'id',
		'createdAt',
		'updatedAt',
	] as const;
	$columns = LinkSchema.$columns;
	@column()
	declare name: string;
	@column()
	declare description: string | null;
	@column()
	declare url: string;
	@column()
	declare favorite: boolean;
	@column()
	declare collectionId: number | null;
	@column()
	declare authorId: number | null;
	@column({ isPrimary: true })
	declare id: number;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class UserSchema extends BaseModel {
	static $columns = [
		'email',
		'name',
		'nickName',
		'avatarUrl',
		'isAdmin',
		'token',
		'providerId',
		'providerType',
		'id',
		'createdAt',
		'updatedAt',
		'lastSeenAt',
	] as const;
	$columns = UserSchema.$columns;
	@column()
	declare email: string;
	@column()
	declare name: string;
	@column()
	declare nickName: string | null;
	@column()
	declare avatarUrl: string;
	@column()
	declare isAdmin: boolean;
	@column()
	declare token: any | null;
	@column()
	declare providerId: string;
	@column()
	declare providerType: string;
	@column({ isPrimary: true })
	declare id: number;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
	@column.dateTime()
	declare lastSeenAt: DateTime | null;
}
