/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ActivityEventTransformer from '#transformers/activity_event_transformer'
import type AuthEventTransformer from '#transformers/auth_event_transformer'
import type CollectionTransformer from '#transformers/collection'
import type LinkTransformer from '#transformers/link'
import type OauthAuthTransformer from '#transformers/oauth_auth_transformer'
import type StatusReportCheckTransformer from '#transformers/status_report_check'
import type UserSessionTransformer from '#transformers/user_session_transformer'
import type UserTransformer from '#transformers/user'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ActivityEvent = InferData<ActivityEventTransformer>
  export namespace ActivityEvent {
    export type Variants = InferVariants<ActivityEventTransformer>
  }
  export type AuthEvent = InferData<AuthEventTransformer>
  export namespace AuthEvent {
    export type Variants = InferVariants<AuthEventTransformer>
  }
  export type Collection = InferData<CollectionTransformer>
  export namespace Collection {
    export type Variants = InferVariants<CollectionTransformer>
  }
  export type Link = InferData<LinkTransformer>
  export namespace Link {
    export type Variants = InferVariants<LinkTransformer>
  }
  export type OauthAuth = InferData<OauthAuthTransformer>
  export namespace OauthAuth {
    export type Variants = InferVariants<OauthAuthTransformer>
  }
  export type StatusReportCheck = InferData<StatusReportCheckTransformer>
  export namespace StatusReportCheck {
    export type Variants = InferVariants<StatusReportCheckTransformer>
  }
  export type UserSession = InferData<UserSessionTransformer>
  export namespace UserSession {
    export type Variants = InferVariants<UserSessionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
