/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type {
	InferData,
	InferVariants,
} from '@adonisjs/core/types/transformers';
import type { InferSharedProps } from '@adonisjs/inertia/types';
import type CollectionTransformer from '#transformers/collection';
import type LinkTransformer from '#transformers/link';
import type SearchResultTransformer from '#transformers/search_result';
import type StatusReportCheckTransformer from '#transformers/status_report_check';
import type UserTransformer from '#transformers/user';
import type InertiaMiddleware from '#middleware/inertia_middleware';

export namespace Data {
	export type Collection = InferData<CollectionTransformer>;
	export namespace Collection {
		export type Variants = InferVariants<CollectionTransformer>;
	}
	export type Link = InferData<LinkTransformer>;
	export namespace Link {
		export type Variants = InferVariants<LinkTransformer>;
	}
	export type SearchResult = InferData<SearchResultTransformer>;
	export namespace SearchResult {
		export type Variants = InferVariants<SearchResultTransformer>;
	}
	export type StatusReportCheck = InferData<StatusReportCheckTransformer>;
	export namespace StatusReportCheck {
		export type Variants = InferVariants<StatusReportCheckTransformer>;
	}
	export type User = InferData<UserTransformer>;
	export namespace User {
		export type Variants = InferVariants<UserTransformer>;
	}
	export type SharedProps = InferSharedProps<InertiaMiddleware>;
}
