// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types';
import type { InferInput } from '@vinejs/vine/types';

type FaviconGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/favicons/favicons_controller.ts').default['render'],
		false
	>;
};
type SharedIdGetHead = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/shared_collections/shared_collection.ts'))['getSharedCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/shared_collections/shared_collections_controller.ts').default['render'],
		true
	>;
};
type UserSettingsGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/user_settings/show_user_settings_controller.ts').default['render'],
		false
	>;
};
type AdminGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/admin/admin_controller.ts').default['render'],
		false
	>;
};
type ApiV1CollectionsGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/api/collections/get_collections_controller.ts').default['render'],
		false
	>;
};
type ApiV1CollectionsPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/create_collection_validator.ts'))['createCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/collections/create_collection_controller.ts').default['execute'],
		true
	>;
};
type ApiV1CollectionsIdPut = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/update_collection_validator.ts'))['updateCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/collections/update_collection_controller.ts').default['execute'],
		true
	>;
};
type ApiV1CollectionsIdDelete = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/delete_collection_validator.ts'))['deleteCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/collections/delete_collection_controller.ts').default['execute'],
		true
	>;
};
type ApiV1LinksPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/create_link_validator.ts'))['createLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/links/create_link_controller.ts').default['execute'],
		true
	>;
};
type ApiV1LinksIdPut = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/update_link_validator.ts'))['updateLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/links/update_link_controller.ts').default['execute'],
		true
	>;
};
type ApiV1LinksIdDelete = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/delete_link_validator.ts'))['deleteLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/api/links/delete_link_controller.ts').default['execute'],
		true
	>;
};
type ApiV1LinksFavoritesGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/api/links/get_favorite_links_controller.ts').default['execute'],
		false
	>;
};
type ApiV1TokensCheckGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/api/tokens/api_token_controller.ts').default['render'],
		false
	>;
};
type AuthCallbackGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/auth/auth_controller.ts').default['callbackAuth'],
		false
	>;
};
type AuthLogoutGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/auth/auth_controller.ts').default['logout'],
		false
	>;
};
type DashboardGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/show_collections_controller.ts').default['render'],
		false
	>;
};
type CollectionsCreateGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/create_collection_controller.ts').default['render'],
		false
	>;
};
type CollectionsPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/create_collection_validator.ts'))['createCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/create_collection_controller.ts').default['execute'],
		true
	>;
};
type CollectionsEditGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/update_collection_controller.ts').default['render'],
		false
	>;
};
type CollectionsIdPut = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/update_collection_validator.ts'))['updateCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/update_collection_controller.ts').default['execute'],
		true
	>;
};
type CollectionsDeleteGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/delete_collection_controller.ts').default['render'],
		false
	>;
};
type CollectionsIdDelete = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/collections/delete_collection_validator.ts'))['deleteCollectionValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/collections/delete_collection_controller.ts').default['execute'],
		true
	>;
};
type LinksCreateGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/links/create_link_controller.ts').default['render'],
		false
	>;
};
type LinksPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/create_link_validator.ts'))['createLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/links/create_link_controller.ts').default['execute'],
		true
	>;
};
type LinksEditGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/links/update_link_controller.ts').default['render'],
		false
	>;
};
type LinksIdPut = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/update_link_validator.ts'))['updateLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/links/update_link_controller.ts').default['execute'],
		true
	>;
};
type LinksIdFavoritePut = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/update_favorite_link_validator.ts'))['updateLinkFavoriteStatusValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/links/toggle_favorite_controller.ts').default['toggleFavorite'],
		true
	>;
};
type LinksDeleteGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/links/delete_link_controller.ts').default['render'],
		false
	>;
};
type LinksIdDelete = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/links/delete_link_validator.ts'))['deleteLinkValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/links/delete_link_controller.ts').default['execute'],
		true
	>;
};
type SearchGetHead = {
	request: unknown;
	response: MakeTuyauResponse<
		import('../app/controllers/search/search_controller.ts').default['render'],
		false
	>;
};
type UserThemePost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/user/update_theme_validator.ts'))['updateThemeValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/user/theme_controller.ts').default['render'],
		true
	>;
};
type UserDisplaypreferencesPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/user/update_display_preferences.ts'))['updateDisplayPreferencesValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/user/display_preferences_controller.ts').default['update'],
		true
	>;
};
type UserApitokensPost = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/user/token/create_api_token.ts'))['createApiTokenValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/user/api_token_controller.ts').default['store'],
		true
	>;
};
type UserApitokensIdDelete = {
	request: MakeTuyauRequest<
		InferInput<
			(typeof import('../app/validators/user/token/delete_api_token.ts'))['deleteApiTokenValidator']
		>
	>;
	response: MakeTuyauResponse<
		import('../app/controllers/user/api_token_controller.ts').default['destroy'],
		true
	>;
};
export interface ApiDefinition {
	favicon: {
		$url: {};
		$get: FaviconGetHead;
		$head: FaviconGetHead;
	};
	shared: {
		':id': {
			$url: {};
			$get: SharedIdGetHead;
			$head: SharedIdGetHead;
		};
	};
	user: {
		settings: {
			$url: {};
			$get: UserSettingsGetHead;
			$head: UserSettingsGetHead;
		};
		theme: {
			$url: {};
			$post: UserThemePost;
		};
		'display-preferences': {
			$url: {};
			$post: UserDisplaypreferencesPost;
		};
		'api-tokens': {
			$url: {};
			$post: UserApitokensPost;
			':tokenId': {
				$url: {};
				$delete: UserApitokensIdDelete;
			};
		};
	};
	admin: {
		$url: {};
		$get: AdminGetHead;
		$head: AdminGetHead;
	};
	api: {
		v1: {
			collections: {
				$url: {};
				$get: ApiV1CollectionsGetHead;
				$head: ApiV1CollectionsGetHead;
				$post: ApiV1CollectionsPost;
				':id': {
					$url: {};
					$put: ApiV1CollectionsIdPut;
					$delete: ApiV1CollectionsIdDelete;
				};
			};
			links: {
				$url: {};
				$post: ApiV1LinksPost;
				':id': {
					$url: {};
					$put: ApiV1LinksIdPut;
					$delete: ApiV1LinksIdDelete;
				};
				favorites: {
					$url: {};
					$get: ApiV1LinksFavoritesGetHead;
					$head: ApiV1LinksFavoritesGetHead;
				};
			};
			tokens: {
				check: {
					$url: {};
					$get: ApiV1TokensCheckGetHead;
					$head: ApiV1TokensCheckGetHead;
				};
			};
		};
	};
	auth: {
		callback: {
			$url: {};
			$get: AuthCallbackGetHead;
			$head: AuthCallbackGetHead;
		};
		logout: {
			$url: {};
			$get: AuthLogoutGetHead;
			$head: AuthLogoutGetHead;
		};
	};
	dashboard: {
		$url: {};
		$get: DashboardGetHead;
		$head: DashboardGetHead;
	};
	collections: {
		create: {
			$url: {};
			$get: CollectionsCreateGetHead;
			$head: CollectionsCreateGetHead;
		};
		$url: {};
		$post: CollectionsPost;
		edit: {
			$url: {};
			$get: CollectionsEditGetHead;
			$head: CollectionsEditGetHead;
		};
		':id': {
			$url: {};
			$put: CollectionsIdPut;
			$delete: CollectionsIdDelete;
		};
		delete: {
			$url: {};
			$get: CollectionsDeleteGetHead;
			$head: CollectionsDeleteGetHead;
		};
	};
	links: {
		create: {
			$url: {};
			$get: LinksCreateGetHead;
			$head: LinksCreateGetHead;
		};
		$url: {};
		$post: LinksPost;
		edit: {
			$url: {};
			$get: LinksEditGetHead;
			$head: LinksEditGetHead;
		};
		':id': {
			$url: {};
			$put: LinksIdPut;
			favorite: {
				$url: {};
				$put: LinksIdFavoritePut;
			};
			$delete: LinksIdDelete;
		};
		delete: {
			$url: {};
			$get: LinksDeleteGetHead;
			$head: LinksDeleteGetHead;
		};
	};
	search: {
		$url: {};
		$get: SearchGetHead;
		$head: SearchGetHead;
	};
}
const routes = [
	{
		params: [],
		name: 'favicon',
		path: '/favicon',
		method: ['GET', 'HEAD'],
		types: {} as FaviconGetHead,
	},
	{
		params: [],
		name: 'home',
		path: '/',
		method: ['GET', 'HEAD'],
		types: {} as unknown,
	},
	{
		params: [],
		name: 'terms',
		path: '/terms',
		method: ['GET', 'HEAD'],
		types: {} as unknown,
	},
	{
		params: [],
		name: 'privacy',
		path: '/privacy',
		method: ['GET', 'HEAD'],
		types: {} as unknown,
	},
	{
		params: ['id'],
		name: 'shared',
		path: '/shared/:id',
		method: ['GET', 'HEAD'],
		types: {} as SharedIdGetHead,
	},
	{
		params: [],
		name: 'user.settings',
		path: '/user/settings',
		method: ['GET', 'HEAD'],
		types: {} as UserSettingsGetHead,
	},
	{
		params: [],
		name: 'admin.dashboard',
		path: '/admin',
		method: ['GET', 'HEAD'],
		types: {} as AdminGetHead,
	},
	{
		params: [],
		name: 'api-collections.index',
		path: '/api/v1/collections',
		method: ['GET', 'HEAD'],
		types: {} as ApiV1CollectionsGetHead,
	},
	{
		params: [],
		name: 'api-collections.create',
		path: '/api/v1/collections',
		method: ['POST'],
		types: {} as ApiV1CollectionsPost,
	},
	{
		params: ['id'],
		name: 'api-collections.update',
		path: '/api/v1/collections/:id',
		method: ['PUT'],
		types: {} as ApiV1CollectionsIdPut,
	},
	{
		params: ['id'],
		name: 'api-collections.delete',
		path: '/api/v1/collections/:id',
		method: ['DELETE'],
		types: {} as ApiV1CollectionsIdDelete,
	},
	{
		params: [],
		name: 'api-links.create',
		path: '/api/v1/links',
		method: ['POST'],
		types: {} as ApiV1LinksPost,
	},
	{
		params: ['id'],
		name: 'api-links.update',
		path: '/api/v1/links/:id',
		method: ['PUT'],
		types: {} as ApiV1LinksIdPut,
	},
	{
		params: ['id'],
		name: 'api-links.delete',
		path: '/api/v1/links/:id',
		method: ['DELETE'],
		types: {} as ApiV1LinksIdDelete,
	},
	{
		params: [],
		name: 'api-links.get-favorite-links',
		path: '/api/v1/links/favorites',
		method: ['GET', 'HEAD'],
		types: {} as ApiV1LinksFavoritesGetHead,
	},
	{
		params: [],
		name: 'api-tokens.index',
		path: '/api/v1/tokens/check',
		method: ['GET', 'HEAD'],
		types: {} as ApiV1TokensCheckGetHead,
	},
	{
		params: [],
		name: 'auth',
		path: '/auth/google',
		method: ['GET', 'HEAD'],
		types: {} as unknown,
	},
	{
		params: [],
		name: 'auth.callback',
		path: '/auth/callback',
		method: ['GET', 'HEAD'],
		types: {} as AuthCallbackGetHead,
	},
	{
		params: [],
		name: 'auth.logout',
		path: '/auth/logout',
		method: ['GET', 'HEAD'],
		types: {} as AuthLogoutGetHead,
	},
	{
		params: [],
		name: 'dashboard',
		path: '/dashboard',
		method: ['GET', 'HEAD'],
		types: {} as DashboardGetHead,
	},
	{
		params: [],
		name: 'collection.create-form',
		path: '/collections/create',
		method: ['GET', 'HEAD'],
		types: {} as CollectionsCreateGetHead,
	},
	{
		params: [],
		name: 'collection.create',
		path: '/collections',
		method: ['POST'],
		types: {} as CollectionsPost,
	},
	{
		params: [],
		name: 'collection.edit-form',
		path: '/collections/edit',
		method: ['GET', 'HEAD'],
		types: {} as CollectionsEditGetHead,
	},
	{
		params: ['id'],
		name: 'collection.edit',
		path: '/collections/:id',
		method: ['PUT'],
		types: {} as CollectionsIdPut,
	},
	{
		params: [],
		name: 'collection.delete-form',
		path: '/collections/delete',
		method: ['GET', 'HEAD'],
		types: {} as CollectionsDeleteGetHead,
	},
	{
		params: ['id'],
		name: 'collection.delete',
		path: '/collections/:id',
		method: ['DELETE'],
		types: {} as CollectionsIdDelete,
	},
	{
		params: [],
		name: 'link.create-form',
		path: '/links/create',
		method: ['GET', 'HEAD'],
		types: {} as LinksCreateGetHead,
	},
	{
		params: [],
		name: 'link.create',
		path: '/links',
		method: ['POST'],
		types: {} as LinksPost,
	},
	{
		params: [],
		name: 'link.edit-form',
		path: '/links/edit',
		method: ['GET', 'HEAD'],
		types: {} as LinksEditGetHead,
	},
	{
		params: ['id'],
		name: 'link.edit',
		path: '/links/:id',
		method: ['PUT'],
		types: {} as LinksIdPut,
	},
	{
		params: ['id'],
		name: 'link.toggle-favorite',
		path: '/links/:id/favorite',
		method: ['PUT'],
		types: {} as LinksIdFavoritePut,
	},
	{
		params: [],
		name: 'link.delete-form',
		path: '/links/delete',
		method: ['GET', 'HEAD'],
		types: {} as LinksDeleteGetHead,
	},
	{
		params: ['id'],
		name: 'link.delete',
		path: '/links/:id',
		method: ['DELETE'],
		types: {} as LinksIdDelete,
	},
	{
		params: [],
		name: 'search',
		path: '/search',
		method: ['GET', 'HEAD'],
		types: {} as SearchGetHead,
	},
	{
		params: [],
		name: 'user.theme',
		path: '/user/theme',
		method: ['POST'],
		types: {} as UserThemePost,
	},
	{
		params: [],
		name: 'user.update-display-preferences',
		path: '/user/display-preferences',
		method: ['POST'],
		types: {} as UserDisplaypreferencesPost,
	},
	{
		params: [],
		name: 'user.api-tokens.store',
		path: '/user/api-tokens',
		method: ['POST'],
		types: {} as UserApitokensPost,
	},
	{
		params: ['tokenId'],
		name: 'user.api-tokens.destroy',
		path: '/user/api-tokens/:tokenId',
		method: ['DELETE'],
		types: {} as UserApitokensIdDelete,
	},
] as const;
export const api = {
	routes,
	definition: {} as ApiDefinition,
};
declare module '@tuyau/inertia/types' {
	type InertiaApi = typeof api;
	export interface Api extends InertiaApi {}
}
